package buildsrc

import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.Internal
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import org.gradle.work.DisableCachingByDefault

private object ProtocolCoverageRenderer {
  private val protocolType = Regex("(?:c2s|bidi)<([A-Za-z0-9_]+)>")
  private val handledType = Regex("on(?:Suspend)?<([A-Za-z0-9_]+)>")

  fun render(protocol: String, handler: String): String {
    val types = protocolType.findAll(protocol).map { it.groupValues[1] }.toSortedSet()
    val handled = handledType.findAll(handler).map { it.groupValues[1] }.toSet()
    val handledCount = types.count { it in handled }
    return buildString {
      appendLine("---")
      appendLine("title: Game protocol coverage")
      appendLine("description: Generated matrix of client-to-server packets and their handler status.")
      appendLine("---")
      appendLine()
      appendLine("<!-- Generated by ./gradlew generateProtocolCoverage. Do not edit by hand. -->")
      appendLine()
      appendLine(
          "The game protocol declares **${types.size}** client-to-server packet types. " +
              "**$handledCount** have an application handler and " +
              "**${types.size - handledCount}** remain unhandled.")
      appendLine()
      appendLine("| Packet | Area | Status |")
      appendLine("| --- | --- | --- |")
      for (type in types) {
        val status = if (type in handled) "Handled" else "Unimplemented"
        appendLine("| `$type` | ${area(type)} | $status |")
      }
    }
  }

  private fun area(type: String): String =
      when {
        type.startsWith("Battle") || type.startsWith("MoveLearn") || type.startsWith("TeamPreview") -> "Battle"
        type.startsWith("Guild") || type.startsWith("TeamName") -> "Guild"
        type.contains("Friend") || type.contains("Social") || type.contains("BlockPlayer") || type.contains("UnblockPlayer") -> "Social"
        type.startsWith("Gtl") || type.contains("Market") -> "Market"
        type.contains("Chat") || type.contains("Message") -> "Chat"
        type.contains("Pokemon") || type.contains("Monster") || type.contains("Party") || type.contains("PcBox") -> "Pokemon"
        type.contains("Map") || type.contains("Movement") || type.contains("Overworld") || type.contains("Entity") || type.contains("Npc") || type.contains("Tile") -> "World"
        type.contains("Character") || type.contains("Join") || type.contains("Auth") -> "Session"
        type.contains("Dialog") -> "Dialog"
        type.contains("Mail") -> "Mail"
        type.contains("Trade") -> "Trade"
        type.contains("Matchmaking") || type.contains("Tournament") || type.contains("Tourney") -> "Matchmaking"
        else -> "Other"
      }
}

@DisableCachingByDefault(because = "Explicitly updates a committed documentation file")
abstract class GenerateProtocolCoverageTask : DefaultTask() {
  @get:InputFile @get:PathSensitive(PathSensitivity.RELATIVE)
  abstract val protocolSource: RegularFileProperty

  @get:InputFile @get:PathSensitive(PathSensitivity.RELATIVE)
  abstract val handlerSource: RegularFileProperty

  @get:Internal abstract val outputFile: RegularFileProperty

  @TaskAction
  fun generate() {
    outputFile.get().asFile.apply {
      parentFile.mkdirs()
      writeText(
          ProtocolCoverageRenderer.render(
              protocolSource.get().asFile.readText(), handlerSource.get().asFile.readText()))
    }
  }
}

@CacheableTask
abstract class CheckProtocolCoverageTask : DefaultTask() {
  @get:InputFile @get:PathSensitive(PathSensitivity.RELATIVE)
  abstract val protocolSource: RegularFileProperty

  @get:InputFile @get:PathSensitive(PathSensitivity.RELATIVE)
  abstract val handlerSource: RegularFileProperty

  @get:InputFile @get:PathSensitive(PathSensitivity.RELATIVE)
  abstract val coverageFile: RegularFileProperty

  @TaskAction
  fun check() {
    val expected =
        ProtocolCoverageRenderer.render(
            protocolSource.get().asFile.readText(), handlerSource.get().asFile.readText())
    if (coverageFile.get().asFile.readText() != expected) {
      throw GradleException(
          "Protocol coverage is stale. Run ./gradlew generateProtocolCoverage and commit the result.")
    }
  }
}
